"""
Sandbox demo-data seeder -- populates a full, realistic dataset for one
real app user (default: 'amit') so you can see how Throughline behaves
with actual density of data, demo it to someone else, and drive the ASMC
volume experiments in mco_asmc/.

Creates 10 richly-profiled Indian-named friend accounts (each with a
distinct personality archetype, LLM-generated conversations, and a
real-looking profile photo) PLUS 100 additional "bulk" friend accounts
(combinatorially generated Indian names, lightweight personality tags,
templated/non-LLM message threads -- these exist for row-volume, not
individually-crafted conversations, so this batch costs no LLM calls).
110 friends total. Friendships with all of them (plus a few friend-to-friend
friendships among the original 10), 100+ text-only direct messages across
Amit<->friend threads AND a few friend<->friend threads (generated by an
LLM per thread so they read as real conversations, not templates), Listen
conversations, tasks/reminders referencing the friends, mood history for
Amit and for each friend's own account, and both the legacy
(personality_notes/speaker_profiles) and newer (emotional_intelligence.*)
EI data models -- so Profiles, Reminders, mood, the weekly digest, and the
friend relationship-insight feature all have real content to show.

Everything this script creates is recorded in demo_data_manifest.json next
to this file. Nothing here touches your real account's own data (Amit's
existing conversations/tasks/etc. are never modified), and running
--cleanup deletes exactly what was seeded and nothing else.

Usage:
    python seed_demo_data.py                  # seed against DATABASE_URL from .env
    python seed_demo_data.py --username amit  # seed for a specific existing user
    python seed_demo_data.py --cleanup        # delete everything this script created

Safety: DATABASE_URL must point at localhost -- this script refuses to run
against anything else, since this is sandbox/demo data, never production.
"""
from __future__ import annotations

import argparse
import json
import os
import random
import re
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path

import psycopg2
import psycopg2.extras
import requests
from dotenv import load_dotenv
from werkzeug.security import generate_password_hash

load_dotenv()

DB_URL = os.getenv("DATABASE_URL")
if not DB_URL:
    raise SystemExit("DATABASE_URL is required (set it in .env)")
if "localhost" not in DB_URL and "127.0.0.1" not in DB_URL:
    raise SystemExit(
        "DATABASE_URL doesn't look like a local database. This script only ever seeds "
        "sandbox/demo data and refuses to run against anything that isn't localhost -- "
        "double-check .env before proceeding."
    )

MANIFEST_PATH = Path(__file__).resolve().parent / "demo_data_manifest.json"
SCHEMA_SQL_PATH = Path(__file__).resolve().parent / "emotional_intelligence" / "emotional_intelligence_schema.sql"

OLLAMA_API_KEY = os.getenv("OLLAMA_API_KEY") or os.getenv("olama_api_key")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "gpt-oss:120b")

MOOD_LABELS = ["happy", "stressed", "calm", "frustrated", "excited", "neutral", "sad", "anxious"]


# ============================================================================
# Personas -- 10 distinct Indian friends, each with a real personality
# archetype that flavors their messages, observations, mood tendencies, and
# relationship profile with Amit, not just a random name.
# ============================================================================
FRIENDS = [
    {
        "first": "Priya", "last": "Sharma", "gender": "women", "photo": 12,
        "archetype": "An enthusiastic planner who's always organizing trips, birthdays, and "
                     "get-togethers for the friend group. Warm, upbeat, uses a lot of exclamation marks.",
        "moods": ["excited", "happy", "happy", "calm"],
        "topics": ["planning a weekend trip to Coorg", "organizing a surprise birthday for a mutual friend",
                   "deciding a restaurant for Friday dinner"],
    },
    {
        "first": "Rohan", "last": "Mehta", "gender": "men", "photo": 32,
        "archetype": "Laid-back with dry, sarcastic humor. Big cricket fan, always has an opinion "
                     "on the latest match. Texts in short, witty one-liners.",
        "moods": ["calm", "happy", "neutral", "frustrated"],
        "topics": ["arguing about last night's IPL match", "roasting each other about fantasy league picks",
                   "planning to watch the weekend match together"],
    },
    {
        "first": "Ananya", "last": "Iyer", "gender": "women", "photo": 45,
        "archetype": "Thoughtful and a little introspective, reads a lot, often shares a quote or "
                     "gives genuinely good advice when someone's stressed.",
        "moods": ["calm", "neutral", "happy", "sad"],
        "topics": ["recommending a book", "talking through a tough decision at work",
                   "catching up after a long gap"],
    },
    {
        "first": "Karan", "last": "Malhotra", "gender": "men", "photo": 51,
        "archetype": "Ambitious and work-focused, recently started a side business, talks fast and "
                     "always seems slightly busy/stressed but in a driven way.",
        "moods": ["stressed", "excited", "stressed", "neutral"],
        "topics": ["a startup idea he's excited about", "asking for advice on a work problem",
                   "venting about a long day at the office"],
    },
    {
        "first": "Sneha", "last": "Reddy", "gender": "women", "photo": 65,
        "archetype": "Warm and family-oriented, a genuine foodie, always talking about what she "
                     "cooked or where to eat. Checks in on people often.",
        "moods": ["happy", "calm", "happy", "excited"],
        "topics": ["a new biryani place she tried", "inviting everyone over for dinner",
                   "checking in on how someone's been doing"],
    },
    {
        "first": "Aditya", "last": "Kapoor", "gender": "men", "photo": 22,
        "archetype": "Adventurous and outdoorsy, into trekking and fitness, always trying to get "
                     "people to join his next trip, high energy.",
        "moods": ["excited", "happy", "calm", "excited"],
        "topics": ["planning a trek for next month", "bragging about a new PB at the gym",
                   "convincing everyone to join a cycling trip"],
    },
    {
        "first": "Neha", "last": "Gupta", "gender": "women", "photo": 68,
        "archetype": "Creative and a bit dramatic in a fun way, into art and music, expressive "
                     "texter who uses a lot of emphasis and voice notes (mentioned, not sent).",
        "moods": ["excited", "happy", "sad", "anxious"],
        "topics": ["a painting she's working on", "a concert she just booked tickets for",
                   "being dramatic about a minor inconvenience"],
    },
    {
        "first": "Vikram", "last": "Nair", "gender": "men", "photo": 41,
        "archetype": "Analytical and precise, works in tech, gives very structured, detailed "
                     "answers even to casual questions. Dry sense of humor.",
        "moods": ["neutral", "calm", "neutral", "happy"],
        "topics": ["debugging a weird bug he found funny", "comparing notes on a new gadget",
                   "planning logistics for a group trip with excessive detail"],
    },
    {
        "first": "Ishita", "last": "Bansal", "gender": "women", "photo": 71,
        "archetype": "Empathetic and calm, the one everyone vents to, asks thoughtful "
                     "follow-up questions, genuinely checks in on people's wellbeing.",
        "moods": ["calm", "happy", "calm", "neutral"],
        "topics": ["checking in after noticing someone seemed off", "talking about managing stress",
                   "planning a low-key hangout, just coffee and talking"],
    },
    {
        "first": "Arjun", "last": "Chawla", "gender": "men", "photo": 29,
        "archetype": "Funny, meme-loving, chaotic energy, sends a lot of short reaction-style "
                     "messages, always the one derailing a serious conversation with a joke.",
        "moods": ["happy", "excited", "neutral", "happy"],
        "topics": ["sending a running joke from the group chat", "chaotic plans that keep changing",
                   "reacting to something ridiculous that happened that day"],
    },
]

FRIEND_FRIEND_PAIRS = [(0, 1), (3, 7), (4, 2)]  # Priya-Rohan, Karan-Vikram, Sneha-Ananya

# ============================================================================
# Bulk friends -- 100 more on top of the 10 richly-profiled ones above,
# combinatorially generated from name pools with lightweight personality
# tags and TEMPLATED (not LLM-written) message threads. This batch exists
# purely for row-volume (friendships/messages/mood/EI rows) to support the
# ASMC experiments -- generating 100 individual LLM conversations would be
# slow and would burn real free-tier API budget for no research benefit,
# so only the original 10 "showcase" friends get LLM-generated threads.
# ============================================================================
BULK_FIRST_MALE = [
    "Rahul", "Amitabh", "Siddharth", "Varun", "Rajesh", "Manish", "Nikhil", "Abhinav",
    "Tarun", "Deepak", "Sameer", "Rajat", "Gaurav", "Ankit", "Ravi", "Suresh",
    "Vivek", "Ajay", "Harsh", "Yash", "Kartik", "Akash", "Ishaan", "Rohit", "Mohit",
]
BULK_FIRST_FEMALE = [
    "Pooja", "Divya", "Kavya", "Shreya", "Meera", "Anjali", "Riya", "Simran",
    "Tanya", "Nisha", "Swati", "Ritu", "Pallavi", "Deepika", "Lakshmi", "Aarti",
    "Bhavna", "Komal", "Shalini", "Preeti", "Radhika", "Juhi", "Manisha", "Sonal", "Payal",
]
BULK_LAST = [
    "Agarwal", "Joshi", "Verma", "Singh", "Rao", "Patel", "Desai", "Pillai",
    "Menon", "Bhat", "Chopra", "Khanna", "Saxena", "Trivedi", "Mishra", "Dubey",
    "Bose", "Chatterjee", "Banerjee", "Sinha", "Kulkarni", "Shah", "Jain", "Goel", "Aggarwal",
]
BULK_TRAITS = [
    "Easygoing and friendly, low-maintenance to talk to.",
    "Quiet but thoughtful, replies take a bit longer but are always considered.",
    "Always up for a plan, rarely says no to hanging out.",
    "Direct and no-nonsense, gets to the point quickly.",
    "Warm and chatty, checks in fairly often.",
    "Busy but reliable, slower to reply but follows through.",
    "Curious and asks a lot of questions, genuinely interested in updates.",
    "Calm under pressure, the one who doesn't overreact to anything.",
]

# Generic exchange templates stitched together to build a plausible-looking
# bulk thread -- deliberately simple string templates, no LLM involved.
BULK_EXCHANGE_TEMPLATES = [
    [("Hey, free this weekend?", "A"), ("Maybe, what's up?", "B"),
     ("Thinking of catching up over coffee", "A"), ("Sounds good, let's do it", "B")],
    [("Did you see the news today?", "A"), ("Yeah, kind of crazy right?", "B"),
     ("Totally wasn't expecting that", "A")],
    [("How's work going?", "A"), ("Busy but okay, you?", "B"),
     ("Same here, barely any time off lately", "A"), ("We should grab lunch sometime", "B")],
    [("Long time! How've you been?", "A"), ("Good good, just been caught up with stuff", "B"),
     ("Same here honestly", "A"), ("We should catch up properly soon", "B")],
    [("Are you coming to the weekend thing?", "A"), ("Trying to, depends on how the day goes", "B"),
     ("Let me know, would be good to see you", "A")],
    [("Random but have you tried that new place near your area?", "A"),
     ("Not yet, is it good?", "B"), ("Pretty decent, we should go sometime", "A"),
     ("Yeah I'm in", "B")],
    [("How was your trip?", "A"), ("So good, needed that break honestly", "B"),
     ("Glad to hear, you deserved it", "A")],
    [("You free for a quick call later?", "A"), ("Yeah should be, after 7?", "B"),
     ("Works for me", "A")],
    [("Saw something that reminded me of you today", "A"), ("Haha what was it", "B"),
     ("Tell you when I see you, it's a long story", "A"), ("Now I have to know", "B")],
    [("Hope things have settled down a bit for you", "A"), ("Slowly but yeah, getting there", "B"),
     ("Good to hear, shout if you need anything", "A")],
]


def generate_bulk_friends(n: int, used_photo_men: set, used_photo_women: set) -> list[dict]:
    pairs_used = set()
    results = []
    men_pool = [i for i in range(100) if i not in used_photo_men]
    women_pool = [i for i in range(100) if i not in used_photo_women]
    random.shuffle(men_pool)
    random.shuffle(women_pool)
    mi = fi = 0
    while len(results) < n:
        gender = random.choice(["men", "women"])
        first = random.choice(BULK_FIRST_MALE if gender == "men" else BULK_FIRST_FEMALE)
        last = random.choice(BULK_LAST)
        key = (first, last)
        if key in pairs_used:
            continue
        pairs_used.add(key)
        if gender == "men":
            photo = men_pool[mi]
            mi += 1
        else:
            photo = women_pool[fi]
            fi += 1
        results.append({
            "first": first, "last": last, "gender": gender, "photo": photo,
            "trait": random.choice(BULK_TRAITS),
        })
    return results


def generate_bulk_conversation(n_messages: int) -> list[dict]:
    turns: list[tuple] = []
    while len(turns) < n_messages:
        turns.extend(random.choice(BULK_EXCHANGE_TEMPLATES))
    return [{"speaker": s, "text": t} for t, s in turns[:n_messages]]


def log(msg: str) -> None:
    print(f"[seed] {msg}", flush=True)


# ============================================================================
# Ollama Cloud call -- same endpoint/convention as
# emotional_intelligence/extraction_pipeline.py's call_llm, reused directly
# here rather than reimplemented a third time.
# ============================================================================
def call_llm(messages: list[dict]) -> str:
    if not OLLAMA_API_KEY:
        raise RuntimeError("Missing Ollama API key (OLLAMA_API_KEY / olama_api_key in .env)")
    response = requests.post(
        "https://ollama.com/api/chat",
        headers={"Authorization": f"Bearer {OLLAMA_API_KEY}", "Content-Type": "application/json"},
        json={"model": OLLAMA_MODEL, "messages": messages, "stream": False},
        timeout=180,
    )
    response.raise_for_status()
    return response.json().get("message", {}).get("content", "")


def extract_json_array(text: str) -> list | None:
    text = text.strip()
    text = re.sub(r"^```json\s*|^```\s*|```$", "", text, flags=re.MULTILINE).strip()
    try:
        return json.loads(text)
    except ValueError:
        pass
    match = re.search(r"\[.*\]", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except ValueError:
            return None
    return None


def generate_conversation(name_a: str, persona_a: str, name_b: str, persona_b: str, topic: str, n_messages: int) -> list[dict]:
    """Returns [{"speaker": "A"|"B", "text": "..."}], via Ollama, with a
    hand-written fallback if the call or parsing fails so seeding never
    hard-crashes on a flaky LLM call."""
    prompt = f"""Write a realistic WhatsApp-style text conversation between two Indian friends.

Person A ({name_a}): {persona_a}
Person B ({name_b}): {persona_b}
Topic: {topic}

Rules:
- Exactly {n_messages} messages total, alternating naturally (occasional back-to-back double-texts from the same person are fine, real chats aren't strictly ping-pong).
- Short, casual, real texting style -- not paragraphs. Occasional Hinglish words are fine (yaar, arre, bhai, acha) but keep it readable.
- Each person's tone must clearly reflect their personality described above.
- Absolutely NO mention of sending, sharing, or receiving photos, images, videos, voice notes, or any attachment -- text only, always.
- Reply with ONLY a JSON array, no preamble, no code fences: [{{"speaker": "A", "text": "..."}}, ...]
- "speaker" must be exactly "A" or "B"."""

    try:
        content = call_llm([{"role": "user", "content": prompt}])
        parsed = extract_json_array(content)
        if parsed and isinstance(parsed, list) and len(parsed) >= 3:
            cleaned = []
            for turn in parsed:
                speaker = turn.get("speaker")
                text = (turn.get("text") or "").strip()
                if speaker in ("A", "B") and text:
                    cleaned.append({"speaker": speaker, "text": text})
            if cleaned:
                return cleaned
    except Exception as exc:
        log(f"  LLM call failed ({exc}), using fallback template for this thread")

    # Fallback -- generic but still two-sided, never leaves a thread empty.
    fallback = [
        ("A", f"heyy, {topic}?"),
        ("B", "haha yeah tell me"),
        ("A", "so what do you think, are you in?"),
        ("B", "100%, count me in"),
        ("A", "perfect, will confirm details soon"),
        ("B", "sounds good!"),
    ]
    return [{"speaker": s, "text": t} for s, t in fallback[:n_messages]]


# ============================================================================
# Timestamp helper -- spreads a thread's messages realistically over the
# last ~10 days, ending recently, with occasional multi-hour/day gaps
# between message clusters instead of one dense burst.
# ============================================================================
def spread_timestamps(n: int, days_back: int = 10) -> list[datetime]:
    now = datetime.now().astimezone()
    start = now - timedelta(days=days_back, hours=random.randint(0, 12))
    stamps = [start]
    for _ in range(n - 1):
        gap_minutes = random.choice([random.randint(1, 15)] * 6 + [random.randint(60, 240)] * 3 + [random.randint(600, 2400)])
        nxt = stamps[-1] + timedelta(minutes=gap_minutes)
        if nxt > now:
            nxt = now - timedelta(minutes=random.randint(0, 30))
        stamps.append(nxt)
    stamps.sort()
    return stamps


# ============================================================================
# Seeding phases
# ============================================================================
def get_user_id(cur, username: str) -> int:
    cur.execute("SELECT id FROM users WHERE username = %s", (username,))
    row = cur.fetchone()
    if not row:
        cur.execute("SELECT username FROM users ORDER BY id LIMIT 20")
        existing = [r[0] for r in cur.fetchall()]
        raise SystemExit(
            f"No user named '{username}' found. Existing usernames (first 20): {existing}\n"
            f"Pass the right one with --username."
        )
    return row[0]


def create_friends(cur, manifest: dict) -> list[dict]:
    log("Creating 10 friend accounts...")
    created = []
    for f in FRIENDS:
        # No "demo"/placeholder-looking text in anything user-visible --
        # these accounts need to read as real friends when showcasing the
        # app, not as obviously-seeded test data.
        username = f"{f['first'].lower()}_{f['last'].lower()}"
        email = f"{f['first'].lower()}.{f['last'].lower()}@example.invalid"
        password_hash = generate_password_hash("sandbox-seed-account-not-a-real-login")
        friend_code = f"{random.randint(100000, 999999)}"
        photo_url = f"https://randomuser.me/api/portraits/{f['gender']}/{f['photo']}.jpg"
        cur.execute(
            "INSERT INTO users (username, email, password_hash, personalization, friend_code, profile_picture_url) "
            "VALUES (%s, %s, %s, 'personal', %s, %s) "
            "ON CONFLICT (username) DO UPDATE SET username = EXCLUDED.username "
            "RETURNING id",
            (username, email, password_hash, friend_code, photo_url),
        )
        user_id = cur.fetchone()[0]
        entry = {**f, "username": username, "user_id": user_id}
        created.append(entry)
        manifest["friend_user_ids"].append(user_id)
        log(f"  {entry['first']} {entry['last']} ({username}) -> user_id {user_id}")
    return created


def create_friendships(cur, amit_id: int, friends: list[dict]) -> None:
    log("Creating friendships...")
    for f in friends:
        # GET /friends displays COALESCE(friendships.nickname, users.username)
        # -- without a nickname on Amit's own friendship row, the UI falls
        # back to the raw lowercase_underscore username instead of a real name.
        full_name = f"{f['first']} {f['last']}"
        cur.execute(
            "INSERT INTO friendships (user_id, friend_id, nickname) VALUES (%s, %s, %s), (%s, %s, NULL) "
            "ON CONFLICT DO NOTHING",
            (amit_id, f["user_id"], full_name, f["user_id"], amit_id),
        )
    for i, j in FRIEND_FRIEND_PAIRS:
        a, b = friends[i]["user_id"], friends[j]["user_id"]
        cur.execute(
            "INSERT INTO friendships (user_id, friend_id) VALUES (%s, %s), (%s, %s) "
            "ON CONFLICT DO NOTHING",
            (a, b, b, a),
        )


def create_bulk_friends(cur, manifest: dict, rich_friends: list[dict], n: int = 100) -> list[dict]:
    log(f"Creating {n} additional bulk friend accounts (templated, no LLM calls)...")
    used_men = {f["photo"] for f in rich_friends if f["gender"] == "men"}
    used_women = {f["photo"] for f in rich_friends if f["gender"] == "women"}
    bulk = generate_bulk_friends(n, used_men, used_women)
    created = []
    for f in bulk:
        username = f"{f['first'].lower()}_{f['last'].lower()}"
        email = f"{f['first'].lower()}.{f['last'].lower()}@example.invalid"
        password_hash = generate_password_hash("sandbox-seed-account-not-a-real-login")
        friend_code = f"{random.randint(100000, 999999)}"
        photo_url = f"https://randomuser.me/api/portraits/{f['gender']}/{f['photo']}.jpg"
        cur.execute(
            "INSERT INTO users (username, email, password_hash, personalization, friend_code, profile_picture_url) "
            "VALUES (%s, %s, %s, 'personal', %s, %s) "
            "ON CONFLICT (username) DO UPDATE SET username = EXCLUDED.username "
            "RETURNING id",
            (username, email, password_hash, friend_code, photo_url),
        )
        user_id = cur.fetchone()[0]
        entry = {**f, "username": username, "user_id": user_id}
        created.append(entry)
        manifest["friend_user_ids"].append(user_id)
    log(f"  created {len(created)} bulk friends -> user_ids {created[0]['user_id']}..{created[-1]['user_id']}")
    return created


def create_bulk_friendships_and_messages(cur, amit_id: int, bulk_friends: list[dict], manifest: dict) -> int:
    log("Creating friendships + templated message threads for bulk friends...")
    total = 0
    for f in bulk_friends:
        full_name = f"{f['first']} {f['last']}"
        cur.execute(
            "INSERT INTO friendships (user_id, friend_id, nickname) VALUES (%s, %s, %s), (%s, %s, NULL) "
            "ON CONFLICT DO NOTHING",
            (amit_id, f["user_id"], full_name, f["user_id"], amit_id),
        )
        n = random.randint(4, 8)
        turns = generate_bulk_conversation(n)
        stamps = spread_timestamps(len(turns), days_back=14)
        for k, (turn, ts) in enumerate(zip(turns, stamps)):
            sender_id = amit_id if turn["speaker"] == "A" else f["user_id"]
            recipient_id = f["user_id"] if turn["speaker"] == "A" else amit_id
            # Leave the last message's tick state unset, same convention as
            # the rich threads -- a thread where every single message is
            # already double-blue-ticked isn't realistic metadata.
            is_recent = k == len(turns) - 1
            delivered = None if is_recent else ts + timedelta(seconds=random.randint(5, 40))
            read = None if is_recent else ts + timedelta(seconds=random.randint(60, 600))
            cur.execute(
                "INSERT INTO direct_messages (sender_id, recipient_id, content, created_at, delivered_at, read_at) "
                "VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
                (sender_id, recipient_id, turn["text"], ts, delivered, read),
            )
            manifest["direct_message_ids"].append(cur.fetchone()[0])
            total += 1
    return total


def seed_calls(cur, amit_id: int, friends: list[dict], manifest: dict) -> int:
    """calls/call_participants -- backs GET /friends' call_count/last_call_at/
    last_call_outgoing (see app.py's friends-list query) and the "Calls"/
    "Last call" rows on the Your World detail card, which otherwise always
    read "No calls yet"/"Never" since nothing else in this script touches
    these tables."""
    log("Seeding call history (calls/call_participants)...")
    total = 0
    now = datetime.now().astimezone()
    for f in friends:
        for i in range(random.randint(1, 3)):
            started = now - timedelta(days=random.randint(0, 13), hours=random.randint(0, 23),
                                       minutes=random.randint(0, 59))
            ended = started + timedelta(minutes=random.randint(1, 25))
            initiator_id = random.choice([amit_id, f["user_id"]])
            room_name = f"call-{amit_id}-{f['user_id']}-{i}-{random.randint(100000, 999999)}"
            cur.execute(
                "INSERT INTO calls (initiator_user_id, room_name, category, status, created_at, ended_at) "
                "VALUES (%s, %s, 'personal', 'ended', %s, %s) RETURNING id",
                (initiator_id, room_name, started, ended),
            )
            call_id = cur.fetchone()[0]
            manifest["call_ids"].append(call_id)
            cur.execute(
                "INSERT INTO call_participants (call_id, user_id, status, joined_at, left_at) "
                "VALUES (%s, %s, 'joined', %s, %s), (%s, %s, 'joined', %s, %s)",
                (call_id, amit_id, started, ended,
                 call_id, f["user_id"], started + timedelta(seconds=random.randint(2, 15)), ended),
            )
            total += 1
    return total


def seed_bulk_profiles_and_mood(cur, amit_id: int, bulk_friends: list[dict], manifest: dict) -> None:
    log("Seeding lightweight Profiles-tab data and mood history for bulk friends...")
    now = datetime.now().astimezone()
    for f in bulk_friends:
        cur.execute(
            "INSERT INTO speaker_profiles (user_id, name) VALUES (%s, %s) "
            "ON CONFLICT (user_id, name) DO UPDATE SET name = EXCLUDED.name RETURNING id",
            (amit_id, f["first"]),
        )
        profile_id = cur.fetchone()[0]
        manifest["speaker_profile_ids"].append(profile_id)

        cur.execute(
            "INSERT INTO personality_notes (user_id, speaker_label, observation, profile_id) "
            "VALUES (%s, %s, %s, %s) RETURNING id",
            (amit_id, f["first"], f["trait"], profile_id),
        )
        manifest["personality_note_ids"].append(cur.fetchone()[0])

        cur.execute(
            "INSERT INTO profile_categories (profile_id, category, first_seen_at, last_seen_at) "
            "VALUES (%s, 'personal', %s, %s) ON CONFLICT (profile_id, category) DO NOTHING",
            (profile_id, now - timedelta(days=10), now),
        )

        # Two entries, not one -- compute_compiled_mood only looks at the
        # live 2-hour bucket or today's most recent entry (app.py's
        # friend_mood). A single entry randomly placed up to 20 hours back
        # often lands before local midnight and shows "Not enough recent
        # data"; anchoring one close to now guarantees a hit either way.
        moods = random.sample(MOOD_LABELS, 2)
        cur.execute(
            "INSERT INTO mood_logs (user_id, mood_label, mood_score, created_at) VALUES (%s, %s, %s, %s) RETURNING id",
            (f["user_id"], moods[0], round(random.uniform(0.6, 0.9), 2), now - timedelta(minutes=random.randint(5, 90))),
        )
        manifest["mood_log_ids"].append(cur.fetchone()[0])
        cur.execute(
            "INSERT INTO mood_logs (user_id, mood_label, mood_score, created_at) VALUES (%s, %s, %s, %s) RETURNING id",
            (f["user_id"], moods[1], round(random.uniform(0.6, 0.9), 2), now - timedelta(hours=random.randint(6, 14))),
        )
        manifest["mood_log_ids"].append(cur.fetchone()[0])


def seed_direct_messages(cur, amit_id: int, amit_persona: str, friends: list[dict], manifest: dict) -> int:
    log("Generating direct-message threads (this calls the LLM per thread, takes a few minutes)...")
    total = 0

    for f in friends:
        n = random.randint(9, 14)
        topic = random.choice(f["topics"])
        log(f"  Amit <-> {f['first']}: {n} messages about '{topic}'")
        turns = generate_conversation("A", amit_persona, "B", f["archetype"], topic, n)
        stamps = spread_timestamps(len(turns))
        for k, (turn, ts) in enumerate(zip(turns, stamps)):
            sender_id = amit_id if turn["speaker"] == "A" else f["user_id"]
            recipient_id = f["user_id"] if turn["speaker"] == "A" else amit_id
            is_recent = k >= len(turns) - 2
            delivered = None if is_recent else ts + timedelta(seconds=random.randint(5, 40))
            read = None if is_recent else ts + timedelta(seconds=random.randint(60, 600))
            cur.execute(
                "INSERT INTO direct_messages (sender_id, recipient_id, content, created_at, delivered_at, read_at) "
                "VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
                (sender_id, recipient_id, turn["text"], ts, delivered, read),
            )
            manifest["direct_message_ids"].append(cur.fetchone()[0])
            total += 1

    for i, j in FRIEND_FRIEND_PAIRS:
        fa, fb = friends[i], friends[j]
        n = random.randint(8, 12)
        topic = random.choice(fa["topics"] + fb["topics"])
        log(f"  {fa['first']} <-> {fb['first']}: {n} messages about '{topic}'")
        turns = generate_conversation("A", fa["archetype"], "B", fb["archetype"], topic, n)
        stamps = spread_timestamps(len(turns), days_back=6)
        for turn, ts in zip(turns, stamps):
            sender_id = fa["user_id"] if turn["speaker"] == "A" else fb["user_id"]
            recipient_id = fb["user_id"] if turn["speaker"] == "A" else fa["user_id"]
            cur.execute(
                "INSERT INTO direct_messages (sender_id, recipient_id, content, created_at, delivered_at, read_at) "
                "VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
                (sender_id, recipient_id, turn["text"], ts,
                 ts + timedelta(seconds=20), ts + timedelta(seconds=200)),
            )
            manifest["direct_message_ids"].append(cur.fetchone()[0])
            total += 1

    return total


CONVERSATION_TEMPLATES = [
    ("Coffee catch-up with Priya", "personal"),
    ("Weekend trek planning with Aditya", "personal"),
    ("Work sync with Karan", "office"),
    ("Family dinner call", "personal"),
    ("Book recommendation chat with Ananya", "personal"),
    ("Cricket match plans with Rohan", "personal"),
]


def seed_conversations(cur, amit_id: int, manifest: dict) -> list[int]:
    log("Creating Amit's Listen-session conversations...")
    conv_ids = []
    for title, category in CONVERSATION_TEMPLATES:
        created_at = datetime.now().astimezone() - timedelta(days=random.randint(1, 9), hours=random.randint(0, 23))
        cur.execute(
            "INSERT INTO conversations (user_id, created_at, title, raw_transcript, category) "
            "VALUES (%s, %s, %s, %s, %s) RETURNING id",
            (amit_id, created_at, title, "...so yeah, that's basically where things stand right now.", category),
        )
        conv_id = cur.fetchone()[0]
        conv_ids.append(conv_id)
        manifest["conversation_ids"].append(conv_id)
    return conv_ids


TASK_TEMPLATES = [
    ("Send Priya the trip itinerary", "personal", -1, "open"),
    ("Call Rohan back about the match tickets", "personal", 0, "open"),
    ("Review the proposal Karan sent", "office", 1, "open"),
    ("Return Ananya's book", "personal", 3, "open"),
    ("Book the campsite for Aditya's trek", "personal", -2, "done"),
    ("Reply to Sneha about dinner plans", "personal", 0, "open"),
    ("Follow up with Vikram on the gadget order", "office", 2, "open"),
    ("Check in with Ishita, she seemed off last week", "personal", -1, "done"),
]


def seed_tasks(cur, amit_id: int, conv_ids: list[int], manifest: dict) -> None:
    log("Creating tasks/reminders...")
    now = datetime.now().astimezone()
    for description, category, day_offset, status in TASK_TEMPLATES:
        conv_id = random.choice(conv_ids)
        reminder_at = now + timedelta(days=day_offset, hours=random.randint(-3, 3))
        due_label = {-2: "2 days ago", -1: "yesterday", 0: "today", 1: "tomorrow"}.get(day_offset, f"in {day_offset} days")
        owner = description.split()[1] if description.split()[0].lower() == "send" else None
        reminder_sent = reminder_at < now  # backdated reminders shouldn't fire a real email on the next nudge pass
        cur.execute(
            "INSERT INTO tasks (user_id, conversation_id, description, owner, due_date, reminder_at, "
            "reminder_sent, status, created_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
            (amit_id, conv_id, description, owner, due_label, reminder_at, reminder_sent, status,
             now - timedelta(days=random.randint(1, 8))),
        )
        manifest["task_ids"].append(cur.fetchone()[0])


def seed_legacy_ei(cur, amit_id: int, friends: list[dict], conv_ids: list[int], manifest: dict) -> None:
    """speaker_profiles/personality_notes/profile_categories (Profiles tab)
    + mood_logs (Amit's own + each friend's own, for GET /friends/<id>/mood)."""
    log("Seeding Profiles-tab data (speaker_profiles/personality_notes) and mood history...")
    now = datetime.now().astimezone()

    for f in friends:
        cur.execute(
            "INSERT INTO speaker_profiles (user_id, name) VALUES (%s, %s) "
            "ON CONFLICT (user_id, name) DO UPDATE SET name = EXCLUDED.name RETURNING id",
            (amit_id, f["first"]),
        )
        profile_id = cur.fetchone()[0]
        manifest["speaker_profile_ids"].append(profile_id)

        conv_id = random.choice(conv_ids)
        cur.execute(
            "INSERT INTO personality_notes (user_id, conversation_id, speaker_label, observation, profile_id) "
            "VALUES (%s, %s, %s, %s, %s) RETURNING id",
            (amit_id, conv_id, f["first"], f["archetype"].split(".")[0] + ".", profile_id),
        )
        manifest["personality_note_ids"].append(cur.fetchone()[0])

        cur.execute(
            "INSERT INTO profile_categories (profile_id, category, first_seen_at, last_seen_at) "
            "VALUES (%s, 'personal', %s, %s) ON CONFLICT (profile_id, category) DO NOTHING",
            (profile_id, now - timedelta(days=8), now),
        )

        # The friend's OWN mood history -- GET /friends/<id>/mood reads
        # mood_logs WHERE user_id = friend_id, so this needs to live on
        # their own account, not Amit's.
        for k, mood in enumerate(f["moods"]):
            logged_at = now - timedelta(hours=k * 6 + random.randint(0, 2))
            cur.execute(
                "INSERT INTO mood_logs (user_id, mood_label, mood_score, created_at) VALUES (%s, %s, %s, %s) RETURNING id",
                (f["user_id"], mood, round(random.uniform(0.6, 0.95), 2), logged_at),
            )
            manifest["mood_log_ids"].append(cur.fetchone()[0])

    # Amit's own mood history, varied across the last couple of days.
    for k, mood in enumerate(["neutral", "happy", "stressed", "calm", "excited", "happy"]):
        logged_at = now - timedelta(hours=k * 5 + random.randint(0, 2))
        conv_id = random.choice(conv_ids)
        cur.execute(
            "INSERT INTO mood_logs (user_id, conversation_id, mood_label, mood_score, created_at) "
            "VALUES (%s, %s, %s, %s, %s) RETURNING id",
            (amit_id, conv_id, mood, round(random.uniform(0.6, 0.95), 2), logged_at),
        )
        manifest["mood_log_ids"].append(cur.fetchone()[0])


AMIT_FACTS = [
    ("works_as", "a software engineer"),
    ("lives_in", "Bangalore"),
    ("is_learning", "to play badminton"),
]
AMIT_BELIEFS = [
    ("work-life balance", "Believes deadlines shouldn't come at the cost of family time"),
    ("friendship", "Believes staying in touch consistently matters more than grand gestures"),
]
AMIT_MEMORIES = [
    ("Had a great trek with Aditya last weekend", "joy", 0.8),
    ("A long, stressful week wrapping up a work deadline", "relief", 0.6),
]
AMIT_PREFERENCES = [
    ("food", "South Indian breakfast"),
    ("hobby", "badminton"),
    ("media", "true crime podcasts"),
]


def seed_new_ei_schema(cur, amit_id: int, friends: list[dict], manifest: dict) -> None:
    """emotional_intelligence.* -- powers the weekly digest and the friend
    relationship-insight surfaced in GET /friends/<id>/mood."""
    log("Applying emotional_intelligence schema (idempotent) and seeding subjects/facts/relationships...")
    if SCHEMA_SQL_PATH.exists():
        cur.execute(SCHEMA_SQL_PATH.read_text(encoding="utf-8"))

    def ensure_subject(user_id: int) -> int:
        canonical = f"app_user:{user_id}"
        cur.execute(
            "INSERT INTO emotional_intelligence.subjects (canonical_name, source) VALUES (%s, 'app_user') "
            "ON CONFLICT (canonical_name) DO UPDATE SET canonical_name = EXCLUDED.canonical_name RETURNING id",
            (canonical,),
        )
        subject_id = cur.fetchone()[0]
        manifest["ei_subject_ids"].append(subject_id)
        cur.execute(
            "INSERT INTO emotional_intelligence.app_user_subject_links (user_id, subject_id) VALUES (%s, %s) "
            "ON CONFLICT (user_id) DO UPDATE SET subject_id = EXCLUDED.subject_id",
            (user_id, subject_id),
        )
        return subject_id

    amit_subject = ensure_subject(amit_id)
    now = datetime.now().astimezone()

    for predicate, obj in AMIT_FACTS:
        cur.execute(
            "INSERT INTO emotional_intelligence.facts (subject_id, subject, predicate, object, confidence, created_at) "
            "VALUES (%s, 'Amit', %s, %s, 0.9, %s) RETURNING id",
            (amit_subject, predicate, obj, now - timedelta(days=random.randint(0, 5))),
        )
        manifest["ei_fact_ids"].append(cur.fetchone()[0])

    for topic, belief in AMIT_BELIEFS:
        cur.execute(
            "INSERT INTO emotional_intelligence.beliefs (subject_id, topic, belief, confidence, created_at) "
            "VALUES (%s, %s, %s, 0.85, %s) RETURNING id",
            (amit_subject, topic, belief, now - timedelta(days=random.randint(0, 5))),
        )
        manifest["ei_belief_ids"].append(cur.fetchone()[0])

    for summary, emotion, importance in AMIT_MEMORIES:
        cur.execute(
            "INSERT INTO emotional_intelligence.memories (subject_id, summary, emotion, importance, created_at) "
            "VALUES (%s, %s, %s, %s, %s) RETURNING id",
            (amit_subject, summary, emotion, importance, now - timedelta(days=random.randint(0, 5))),
        )
        manifest["ei_memory_ids"].append(cur.fetchone()[0])

    for category, item in AMIT_PREFERENCES:
        cur.execute(
            "INSERT INTO emotional_intelligence.preferences (subject_id, category, item, weight, confidence, updated_at) "
            "VALUES (%s, %s, %s, 0.8, 0.85, %s) "
            "ON CONFLICT (subject_id, category, item) DO UPDATE SET updated_at = EXCLUDED.updated_at RETURNING id",
            (amit_subject, category, item, now),
        )
        manifest["ei_preference_ids"].append(cur.fetchone()[0])

    cur.execute(
        "INSERT INTO emotional_intelligence.personality_snapshots "
        "(subject_id, openness, conscientiousness, extraversion, agreeableness, neuroticism, confidence, created_at) "
        "VALUES (%s, 0.72, 0.68, 0.55, 0.8, 0.4, 0.75, %s) RETURNING id",
        (amit_subject, now),
    )
    manifest["ei_personality_snapshot_ids"].append(cur.fetchone()[0])

    # Relationship profiles -- one per friend, trust/conflict/support varied
    # to roughly match their archetype (Priya/Sneha/Ishita read as closer;
    # Karan reads as more transactional/lower-touch).
    relationship_flavor = {
        "Priya": (0.9, 0.85, 0.05, 0.85, "You two plan most trips together and check in almost daily."),
        "Rohan": (0.8, 0.6, 0.15, 0.6, "Mostly banter and cricket talk, but he's reliable when it matters."),
        "Ananya": (0.85, 0.5, 0.05, 0.9, "A go-to for real conversations when something's actually on your mind."),
        "Karan": (0.6, 0.35, 0.2, 0.4, "Friendly but infrequent -- mostly work-adjacent check-ins."),
        "Sneha": (0.88, 0.7, 0.05, 0.8, "Warm and consistent, usually the one keeping the group connected."),
        "Aditya": (0.75, 0.55, 0.1, 0.6, "Bonded mostly over treks and fitness, lower-key otherwise."),
        "Neha": (0.7, 0.5, 0.25, 0.65, "Fun and expressive, occasional friendly friction over plans changing."),
        "Vikram": (0.65, 0.4, 0.1, 0.5, "Practical relationship, mostly logistics and shared interests in tech."),
        "Ishita": (0.92, 0.65, 0.02, 0.95, "The friend who actually checks in on how you're doing."),
        "Arjun": (0.78, 0.6, 0.1, 0.6, "Low-stakes and fun, always good for a laugh, not for deep talks."),
    }

    for f in friends:
        friend_subject = ensure_subject(f["user_id"])
        if f["first"] in relationship_flavor:
            trust, freq, conflict, support, summary = relationship_flavor[f["first"]]
            topics = f["topics"][:2]
        else:
            # Bulk friend -- no hand-written flavor, generate a plausible
            # generic one instead (still no LLM call).
            trust = round(random.uniform(0.55, 0.85), 2)
            freq = round(random.uniform(0.2, 0.6), 2)
            conflict = round(random.uniform(0.02, 0.2), 2)
            support = round(random.uniform(0.4, 0.75), 2)
            summary = f["trait"]
            topics = ["catching up"]
        sa, sb = sorted([amit_subject, friend_subject])
        cur.execute(
            "INSERT INTO emotional_intelligence.relationship_profiles "
            "(subject_a, subject_b, trust_score, communication_frequency, conflict_score, emotional_support, "
            "humor_similarity, shared_topics, relationship_summary, updated_at) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (subject_a, subject_b) DO UPDATE SET relationship_summary = EXCLUDED.relationship_summary "
            "RETURNING id",
            (sa, sb, trust, freq, conflict, support, round(random.uniform(0.5, 0.9), 2),
             topics, summary, now),
        )
        manifest["ei_relationship_profile_ids"].append(cur.fetchone()[0])

    # Bilateral cognitive sharing for a few close friends, so the gated
    # relationship-insight/common-ground feature has something real to show.
    for f in friends[:3]:
        cur.execute(
            "INSERT INTO cognitive_sharing_settings (user_id, friend_id, level, updated_at) "
            "VALUES (%s, %s, 'collaborative', %s), (%s, %s, 'collaborative', %s) "
            "ON CONFLICT (user_id, friend_id) DO UPDATE SET level = EXCLUDED.level",
            (amit_id, f["user_id"], now, f["user_id"], amit_id, now),
        )


def build_manifest() -> dict:
    return {
        "created_at": datetime.now().astimezone().isoformat(),
        "amit_username": None,
        "friend_user_ids": [],
        "direct_message_ids": [],
        "conversation_ids": [],
        "task_ids": [],
        "speaker_profile_ids": [],
        "personality_note_ids": [],
        "mood_log_ids": [],
        "ei_subject_ids": [],
        "ei_fact_ids": [],
        "ei_belief_ids": [],
        "ei_memory_ids": [],
        "ei_preference_ids": [],
        "ei_personality_snapshot_ids": [],
        "ei_relationship_profile_ids": [],
        "call_ids": [],
    }


def seed(username: str) -> None:
    if MANIFEST_PATH.exists():
        raise SystemExit(
            f"{MANIFEST_PATH.name} already exists -- looks like demo data was already seeded. "
            f"Run `python seed_demo_data.py --cleanup` first if you want to reseed."
        )

    conn = psycopg2.connect(DB_URL)
    conn.autocommit = False
    manifest = build_manifest()
    manifest["amit_username"] = username
    try:
        cur = conn.cursor()
        amit_id = get_user_id(cur, username)
        log(f"Seeding demo data for '{username}' (user_id {amit_id})")
        amit_persona = ("The main user -- balanced, friendly, generally upbeat but occasionally "
                         "stressed with work, texts in a normal casual style.")

        friends = create_friends(cur, manifest)
        create_friendships(cur, amit_id, friends)
        total_messages = seed_direct_messages(cur, amit_id, amit_persona, friends, manifest)
        conv_ids = seed_conversations(cur, amit_id, manifest)
        seed_tasks(cur, amit_id, conv_ids, manifest)
        seed_legacy_ei(cur, amit_id, friends, conv_ids, manifest)

        bulk_friends = create_bulk_friends(cur, manifest, friends, n=100)
        bulk_messages = create_bulk_friendships_and_messages(cur, amit_id, bulk_friends, manifest)
        seed_bulk_profiles_and_mood(cur, amit_id, bulk_friends, manifest)
        total_messages += bulk_messages

        all_friends = friends + bulk_friends
        seed_new_ei_schema(cur, amit_id, all_friends, manifest)
        seed_calls(cur, amit_id, all_friends, manifest)

        conn.commit()
        MANIFEST_PATH.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
        log(f"Done. {len(all_friends)} friends total ({len(friends)} rich + {len(bulk_friends)} bulk), "
            f"{total_messages} direct messages across {len(friends) + len(FRIEND_FRIEND_PAIRS) + len(bulk_friends)} threads.")
        log(f"Manifest written to {MANIFEST_PATH} -- run --cleanup anytime to remove all of this.")
        log("Note: NUDGE_FEATURE_ENABLED=False in .env -- flip it to true if you want the "
            "overdue-task/mood-trend/relationship nudges to actually fire off this data.")
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def cleanup() -> None:
    if not MANIFEST_PATH.exists():
        raise SystemExit(f"No {MANIFEST_PATH.name} found -- nothing to clean up.")
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))

    conn = psycopg2.connect(DB_URL)
    conn.autocommit = False
    try:
        cur = conn.cursor()
        log(f"Deleting {len(manifest['friend_user_ids'])} fake friend accounts (cascades their friendships, "
            "sent/received messages, own mood history, and EI subjects/facts/relationship rows)...")
        if manifest["friend_user_ids"]:
            cur.execute("DELETE FROM users WHERE id = ANY(%s)", (manifest["friend_user_ids"],))

        # Everything below is owned by Amit's own account, so it's cleaned
        # up explicitly by id rather than relying on any cascade.
        table_id_pairs = [
            ("direct_messages", "direct_message_ids"),
            ("personality_notes", "personality_note_ids"),
            ("mood_logs", "mood_log_ids"),
            ("tasks", "task_ids"),
            ("speaker_profiles", "speaker_profile_ids"),
            ("conversations", "conversation_ids"),
            ("calls", "call_ids"),  # call_participants cascade-deletes via calls.id
        ]
        for table, key in table_id_pairs:
            ids = manifest.get(key) or []
            if ids:
                cur.execute(f"DELETE FROM {table} WHERE id = ANY(%s)", (ids,))

        ei_table_id_pairs = [
            ("emotional_intelligence.relationship_profiles", "ei_relationship_profile_ids"),
            ("emotional_intelligence.personality_snapshots", "ei_personality_snapshot_ids"),
            ("emotional_intelligence.preferences", "ei_preference_ids"),
            ("emotional_intelligence.memories", "ei_memory_ids"),
            ("emotional_intelligence.beliefs", "ei_belief_ids"),
            ("emotional_intelligence.facts", "ei_fact_ids"),
        ]
        for table, key in ei_table_id_pairs:
            ids = manifest.get(key) or []
            if ids:
                cur.execute(f"DELETE FROM {table} WHERE id = ANY(%s)", (ids,))

        # Amit's own EI subject row (friends' own subject rows are already
        # gone via the CASCADE from deleting their user row above).
        amit_id = get_user_id(cur, manifest["amit_username"])
        cur.execute(
            "DELETE FROM emotional_intelligence.app_user_subject_links WHERE user_id = %s RETURNING subject_id",
            (amit_id,),
        )
        row = cur.fetchone()
        if row:
            cur.execute("DELETE FROM emotional_intelligence.subjects WHERE id = %s", (row[0],))

        conn.commit()
        log("Cleanup complete.")
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

    MANIFEST_PATH.unlink()
    log(f"Removed {MANIFEST_PATH.name}.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--username", default="amit", help="Existing account to seed friends/data for (default: amit)")
    parser.add_argument("--cleanup", action="store_true", help="Delete everything this script previously seeded")
    args = parser.parse_args()

    if args.cleanup:
        cleanup()
    else:
        seed(args.username)


if __name__ == "__main__":
    main()
